import json

nb = json.load(open('c:/betting_prediction_model/nba-betting-model/notebooks/training.ipynb', encoding='utf-8'))

# ── CELL 18 ──────────────────────────────────────────────────────────────────
cell18 = (
    "# ── LightGBM + Logistic Meta-Stacker ────────────────────────────────────────\n"
    "# XGBoost: depth-wise trees. LightGBM: leaf-wise trees. Different errors.\n"
    "# Logistic meta-stacker learns the optimal combination from validation preds.\n"
    "import lightgbm as lgb\n"
    "from sklearn.linear_model import LogisticRegression\n"
    "\n"
    "# ── LightGBM (improved params) ───────────────────────────────────────────────\n"
    "# num_leaves=63 (was 31): more expressive. subsample_freq=5: gradient-based sampling.\n"
    "lgbm_model = lgb.LGBMClassifier(\n"
    "    objective         = 'binary',\n"
    "    metric            = 'binary_logloss',\n"
    "    learning_rate     = 0.02,\n"
    "    num_leaves        = 63,\n"
    "    max_depth         = -1,\n"
    "    min_child_samples = 30,\n"
    "    subsample         = 0.85,\n"
    "    subsample_freq    = 5,\n"
    "    colsample_bytree  = 0.75,\n"
    "    reg_alpha         = 0.1,\n"
    "    reg_lambda        = 2.0,\n"
    "    n_estimators      = 1500,\n"
    "    random_state      = 42,\n"
    "    verbosity         = -1,\n"
    ")\n"
    "lgbm_model.fit(\n"
    "    X_train, y_train,\n"
    "    eval_set  = [(X_valid, y_valid)],\n"
    "    callbacks = [\n"
    "        lgb.early_stopping(stopping_rounds=60, verbose=False),\n"
    "        lgb.log_evaluation(period=-1),\n"
    "    ],\n"
    ")\n"
    "print(f'LGBM best iteration : {lgbm_model.best_iteration_}')\n"
    "\n"
    "# ── Probabilities from each base model ───────────────────────────────────────\n"
    "xgb_val_probs   = final_model.predict_proba(X_valid)[:, 1]\n"
    "lgbm_val_probs  = lgbm_model.predict_proba(X_valid)[:, 1]\n"
    "xgb_test_probs  = final_model.predict_proba(X_test)[:, 1]\n"
    "lgbm_test_probs = lgbm_model.predict_proba(X_test)[:, 1]\n"
    "\n"
    "# ── Logistic meta-stacker ─────────────────────────────────────────────────────\n"
    "val_meta  = np.column_stack([xgb_val_probs, lgbm_val_probs])\n"
    "test_meta = np.column_stack([xgb_test_probs, lgbm_test_probs])\n"
    "\n"
    "stacker = LogisticRegression(C=1.0, fit_intercept=True, max_iter=1000, random_state=42)\n"
    "stacker.fit(val_meta, y_valid)\n"
    "\n"
    "stack_val_probs  = stacker.predict_proba(val_meta)[:, 1]\n"
    "stack_test_probs = stacker.predict_proba(test_meta)[:, 1]\n"
    "\n"
    "xgb_w, lgbm_w = stacker.coef_[0]\n"
    "print(f'Stacker coefs  : XGB={xgb_w:.3f}  LGBM={lgbm_w:.3f}  bias={stacker.intercept_[0]:.3f}')\n"
    "\n"
    "# ── 50/50 blend (robust fallback) ────────────────────────────────────────────\n"
    "blend_val_probs  = 0.5 * xgb_val_probs  + 0.5 * lgbm_val_probs\n"
    "blend_test_probs = 0.5 * xgb_test_probs + 0.5 * lgbm_test_probs\n"
    "\n"
    "# ── Validation AUC comparison ────────────────────────────────────────────────\n"
    "val_aucs = {\n"
    "    'XGBoost'    : roc_auc_score(y_valid, xgb_val_probs),\n"
    "    'LightGBM'   : roc_auc_score(y_valid, lgbm_val_probs),\n"
    "    '50/50 blend': roc_auc_score(y_valid, blend_val_probs),\n"
    "    'Stacker'    : roc_auc_score(y_valid, stack_val_probs),\n"
    "}\n"
    "print('Validation AUC:')\n"
    "for name, auc_v in sorted(val_aucs.items(), key=lambda x: -x[1]):\n"
    "    print(f'  {name:<14}: {auc_v:.4f}')\n"
    "\n"
    "# Use stacker as the primary ensemble output for downstream cells\n"
    "ensemble_val_probs  = stack_val_probs\n"
    "ensemble_test_probs = stack_test_probs\n"
    "print('Using Stacker as primary ensemble output.')\n"
)

# ── CELL 27 ──────────────────────────────────────────────────────────────────
cell27 = (
    "# ── Calibrate XGBoost, LightGBM, and Stacker ─────────────────────────────────\n"
    "from sklearn.calibration import CalibratedClassifierCV, calibration_curve\n"
    "from sklearn.isotonic import IsotonicRegression\n"
    "\n"
    "# Calibrate XGBoost\n"
    "try:\n"
    "    from sklearn.frozen import FrozenEstimator\n"
    "    xgb_cal = CalibratedClassifierCV(FrozenEstimator(final_model), method='isotonic', cv=None)\n"
    "except ImportError:\n"
    "    xgb_cal = CalibratedClassifierCV(final_model, method='isotonic', cv='prefit')\n"
    "xgb_cal.fit(X_valid, y_valid)\n"
    "\n"
    "# Calibrate LightGBM\n"
    "try:\n"
    "    lgbm_cal = CalibratedClassifierCV(FrozenEstimator(lgbm_model), method='isotonic', cv=None)\n"
    "except Exception:\n"
    "    lgbm_cal = CalibratedClassifierCV(lgbm_model, method='isotonic', cv='prefit')\n"
    "lgbm_cal.fit(X_valid, y_valid)\n"
    "\n"
    "# Calibrate Stacker via isotonic regression on its own validation probs\n"
    "iso_stacker = IsotonicRegression(out_of_bounds='clip')\n"
    "iso_stacker.fit(stack_val_probs, y_valid)\n"
    "\n"
    "# Test-set calibrated probabilities\n"
    "xgb_cal_test   = xgb_cal.predict_proba(X_test)[:, 1]\n"
    "lgbm_cal_test  = lgbm_cal.predict_proba(X_test)[:, 1]\n"
    "stack_cal_test = iso_stacker.predict(stack_test_probs)\n"
    "\n"
    "# ── Full comparison table ─────────────────────────────────────────────────────\n"
    "candidates = {\n"
    "    'XGB raw'        : xgb_test_probs,\n"
    "    'XGB calibrated' : xgb_cal_test,\n"
    "    'LGBM raw'       : lgbm_test_probs,\n"
    "    'LGBM calibrated': lgbm_cal_test,\n"
    "    'Stacker raw'    : stack_test_probs,\n"
    "    'Stacker cal'    : stack_cal_test,\n"
    "}\n"
    "print(f\"{'Model':<20} {'AUC':>7} {'Acc @thr':>10} {'Brier':>8}\")\n"
    "print('-' * 50)\n"
    "best_acc, best_name, best_probs = 0, '', None\n"
    "for name, probs in candidates.items():\n"
    "    auc_s = roc_auc_score(y_test, probs)\n"
    "    acc_s = accuracy_score(y_test, (probs >= FINAL_THRESHOLD).astype(int))\n"
    "    bri_s = brier_score_loss(y_test, probs)\n"
    "    marker = ' <-- BEST' if acc_s > best_acc else ''\n"
    "    if acc_s > best_acc:\n"
    "        best_acc, best_name, best_probs = acc_s, name, probs\n"
    "    print(f'{name:<20} {auc_s:>7.4f} {acc_s:>10.4f} {bri_s:>8.4f}{marker}')\n"
    "\n"
    "print(f'Best model: {best_name}  ->  {best_acc:.4f} ({best_acc:.1%})')\n"
    "\n"
    "# Set cal_probs to best for summary cell\n"
    "cal_probs = best_probs\n"
    "calibrated_model = xgb_cal\n"
    "\n"
    "# ── Reliability diagram for top 3 ─────────────────────────────────────────────\n"
    "fig, axes = plt.subplots(1, 3, figsize=(21, 6))\n"
    "for (title, probs), ax in zip(\n"
    "    [('XGB calibrated', xgb_cal_test),\n"
    "     ('LGBM calibrated', lgbm_cal_test),\n"
    "     ('Stacker cal', stack_cal_test)],\n"
    "    axes\n"
    "):\n"
    "    frac_pos, mean_pred = calibration_curve(y_test, probs, n_bins=10)\n"
    "    ax.plot(mean_pred, frac_pos, 'o-', color='#2196F3', linewidth=2.5, label='Model')\n"
    "    ax.plot([0, 1], [0, 1], 'k--', label='Perfect')\n"
    "    ax.set_title(title)\n"
    "    ax.set_xlabel('Mean Predicted Probability')\n"
    "    ax.set_ylabel('Fraction of Positives')\n"
    "    ax.set_xlim(0, 1); ax.set_ylim(0, 1)\n"
    "    ax.grid(True, alpha=0.25); ax.legend()\n"
    "plt.suptitle('Reliability Diagrams', fontsize=15, fontweight='bold')\n"
    "fig.tight_layout()\n"
    "plt.show()\n"
)

# ── CELL 32 ──────────────────────────────────────────────────────────────────
cell32 = (
    "import json as _json\n"
    "from datetime import datetime\n"
    "timestamp = datetime.now().strftime('%Y%m%d_%H%M')\n"
    "\n"
    "# 1. XGBoost\n"
    "xgb_path = f'{MODELS_DIR}/xgb_nba_{timestamp}.json'\n"
    "final_model.save_model(xgb_path)\n"
    "print(f'Saved XGBoost          : {xgb_path}')\n"
    "\n"
    "# 2. LightGBM\n"
    "lgbm_path = f'{MODELS_DIR}/lgbm_nba_{timestamp}.joblib'\n"
    "joblib.dump(lgbm_model, lgbm_path)\n"
    "print(f'Saved LightGBM         : {lgbm_path}')\n"
    "\n"
    "# 3. Stacker\n"
    "stacker_path = f'{MODELS_DIR}/stacker_{timestamp}.joblib'\n"
    "joblib.dump(stacker, stacker_path)\n"
    "print(f'Saved stacker          : {stacker_path}')\n"
    "\n"
    "# 4. Calibrated XGBoost\n"
    "cal_path = f'{MODELS_DIR}/xgb_calibrated_{timestamp}.joblib'\n"
    "joblib.dump(calibrated_model, cal_path)\n"
    "print(f'Saved XGB calibrated   : {cal_path}')\n"
    "\n"
    "# 5. Isotonic calibrator for stacker\n"
    "iso_path = f'{MODELS_DIR}/iso_stacker_{timestamp}.joblib'\n"
    "joblib.dump(iso_stacker, iso_path)\n"
    "print(f'Saved stacker isotonic : {iso_path}')\n"
    "\n"
    "# 6. Feature list\n"
    "feat_path = f'{MODELS_DIR}/feature_list_{timestamp}.json'\n"
    "with open(feat_path, 'w') as f:\n"
    "    _json.dump(ALL_FEATURES, f, indent=2)\n"
    "print(f'Saved feature list     : {feat_path}')\n"
    "\n"
    "# 7. Metadata\n"
    "meta = {\n"
    "    'timestamp'      : timestamp,\n"
    "    'train_seasons'  : f'2003-{TRAIN_END}',\n"
    "    'valid_seasons'  : f'{VALID_START}-{VALID_END}',\n"
    "    'test_season'    : str(TEST_START),\n"
    "    'n_features'     : len(ALL_FEATURES),\n"
    "    'n_train_rows'   : len(X_train),\n"
    "    'test_auc_xgb'   : round(roc_auc_score(y_test, xgb_test_probs), 4),\n"
    "    'test_auc_lgbm'  : round(roc_auc_score(y_test, lgbm_test_probs), 4),\n"
    "    'test_auc_stack' : round(roc_auc_score(y_test, stack_test_probs), 4),\n"
    "    'best_model'     : best_name,\n"
    "    'best_accuracy'  : round(best_acc, 4),\n"
    "    'xgb_best_iter'  : final_model.best_iteration,\n"
    "    'lgbm_best_iter' : lgbm_model.best_iteration_,\n"
    "    'stacker_coefs'  : {'xgb': round(float(xgb_w), 4), 'lgbm': round(float(lgbm_w), 4)},\n"
    "    'best_params_xgb': best_params,\n"
    "}\n"
    "meta_path = f'{MODELS_DIR}/model_meta_{timestamp}.json'\n"
    "with open(meta_path, 'w') as f:\n"
    "    _json.dump(meta, f, indent=2)\n"
    "print(f'Saved metadata         : {meta_path}')\n"
    "print(f'All artifacts saved to : {MODELS_DIR}/')\n"
)

for ci, src in [(18, cell18), (27, cell27), (32, cell32)]:
    nb['cells'][ci]['source'] = src
    nb['cells'][ci]['outputs'] = []
    nb['cells'][ci]['execution_count'] = None

with open('c:/betting_prediction_model/nba-betting-model/notebooks/training.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)
print("Saved")
